language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install: composer install --no-interaction

before_script:
  - mkdir build
  - mkdir build/cov

script: phpunit

after_success:
  # CodeClimate.com
  - vendor/bin/test-reporter