name: test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.5 ]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.after }}
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - name: Install dependencies
        run: composer install --no-interaction
      - name: Lint
        run: ./vendor/bin/phpcs
      - name: Test
        run: ./vendor/bin/phpunit --coverage-clover coverage/clover.xml
      - name: Report Coverage
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/clover.xml
